Repository foss3/runtime-pallet-library, pull requests merged in 2023-10, with the labels that each got.

#1 MockBuilder: add support for traits with methods with the same name
  mock-builder/src/lib.rs
  mock-builder/src/location.rs
  mock-builder/tests/pallet.rs
Labels: enhancement

#3 feat: add simple GitHub actions
  .github/dependabot.yml
  .github/workflows/sanity-checks.yml
  rust-toolchain.toml
Labels: enhancement

#4 ci: add docs github actions
  .github/workflows/docs.yml
Labels: enhancement

#7 ci: split sanity checks
  .github/workflows/clippy.yml
  .github/workflows/lints.yml
  .github/workflows/tests.yml
Labels: enhancement

#5 docs: improve readme
  README.md
Labels: documentation

#6 chore: synch with Substrate
  .github/workflows/clippy.yml
  .github/workflows/lints.yml
  .github/workflows/tests.yml
  .gitignore
  Cargo.toml
  mock-builder/src/location.rs
  rust-toolchain.toml
  rustfmt.toml
Labels: enhancement

#8 Docs: visual issue
  mock-builder/src/lib.rs
Labels: documentation

#9 Upgrade to Polkadot v1.0.0
  Cargo.toml
  mock-builder/src/lib.rs
  mock-builder/tests/pallet.rs
Labels: release

#11 Remove hashes from storages
  mock-builder/CHANGELOG.md
  mock-builder/Cargo.toml
  mock-builder/src/lib.rs
  mock-builder/src/location.rs
  mock-builder/tests/pallet.rs
Labels: enhancement

#10 Upgrade to Polkadot v1.1.0
  Cargo.toml
Labels: release

#12 Upgrade Polkadot version to v1.2.0
  Cargo.toml
Labels: release
